### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by pandalec** [Adi146/home-assistant-kubernetes#6]
Hi! 

I run into the following error when I enable this plugin via HACS. Kubernetes config file lies in the hass config folder.

```
Error setting up entry kubernetes for kubernetes

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kubernetes/__init__.py", line 32, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```
Version:
Home Assistant 2023.10.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231005.0 - latest 

Is there anything I can do?

BR

**Comment by alec-pinson** [comment]
Same for me
